export type { CSSProperties } from "./CSSProperties";

export { border } from "./expanders/border";
export { borderColor } from "./expanders/borderColor";
export { borderImage } from "./expanders/borderImage";
export { borderRadius } from "./expanders/borderRadius";
export { borderStyle } from "./expanders/borderStyle";
export { borderWidth } from "./expanders/borderWidth";
export { flex } from "./expanders/flex";
export { flexFlow } from "./expanders/flexFlow";
export { gap } from "./expanders/gap";
export { inset } from "./expanders/inset";
export { lineClamp } from "./expanders/lineClamp";
export { listStyle } from "./expanders/listStyle";
export { margin } from "./expanders/margin";
export { outline } from "./expanders/outline";
export { overflow } from "./expanders/overflow";
export { padding } from "./expanders/padding";
export { placeContent } from "./expanders/placeContent";
export { placeItems } from "./expanders/placeItems";
export { placeSelf } from "./expanders/placeSelf";
export { textDecoration } from "./expanders/textDecoration";
export { textEmphasis } from "./expanders/textEmphasis";
export { transition } from "./expanders/transition";
